databases:
- name: mafia-postgres
  databaseName: mafia
  user: mafia
  plan: free

services:
- type: web
  name: mafia-bot-web
  runtime: node
  plan: free
  buildCommand: npm ci --only=production
  startCommand: npm start
  autoDeploy: true
  healthCheckPath: /health
  envVars:
  - key: DATABASE_URL
    fromDatabase:
      name: mafia-postgres
      property: connectionString
  - key: ADMIN_TOKEN
    generateValue: true
  - key: BOT_TOKEN_INTERNAL
    generateValue: true
  - key: NODE_ENV
    value: production
  - key: PORT
    value: 10000